name: 20100-almalinux9

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: 20100 almalinux9 build system
    runs-on: ubuntu-24.04
    timeout-minutes: 7200
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4
      - name: Setup nodejs 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: ISO build
        run: |
          ./20100-almalinux9-container-test.sh
      - name: ISO export
        uses: actions/upload-artifact@v4
        with:
          name: egg-of_almalinux-9-minimal_amd64_latest
          path: ./mychroot/ci/iso/egg-of*.iso
          retention-days: 1
          if-no-files-found: warn
          compression-level: 0
          overwrite: true
          include-hidden-files: false          
      
