name: Build Alpine Linux Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Prepare Build Environment
        run: |
          apk update
          # AGGIUNTO 'sudo' alla lista dei pacchetti da installare
          apk add alpine-sdk git nodejs npm sudo

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Create Build User and Keys
        run: |
          adduser -D builder
          addgroup builder abuild
          
          # Ora questo comando funzionera' perche' 'sudo' esiste
          sudo -u builder abuild-keygen -a -i
          
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build The Package as Non-Root User
        run: sudo -u builder abuild -r
        working-directory: ./packaging/alpine
        
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-package
          path: /home/builder/packages/**/*.apk

