name: Build Fedora Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpm-fedora:
    runs-on: ubuntu-latest
    
    container:
      image: fedora:42

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Download Bootloaders
        run: curl -LO https://github.com/pieroproietti/penguins-bootloaders/releases/download/v25.9.8/bootloaders.tar.gz

      - name: 3. Install Build Dependencies
        run: |
          dnf install -y rpm-build dnf-plugins-core git tar gzip
          dnf builddep -y ./packaging/rpm/penguins-eggs.spec

      - name: 4. Prepare RPM Sources
        run: |
          git config --global --add safe.directory /github/workspace
          mkdir -p $HOME/rpmbuild/SOURCES
          git archive --format=tar.gz --output=$HOME/rpmbuild/SOURCES/penguins-eggs-25.9.8.tar.gz HEAD
          cp bootloaders.tar.gz $HOME/rpmbuild/SOURCES/

      - name: 5. Build RPM package
        run: rpmbuild -ba ./packaging/rpm/penguins-eggs.spec

      - name: 6. Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-42-rpm
          path: ~/rpmbuild/RPMS/**/*.rpm