name: Build Arch Linux Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pkg-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Prepare Build Environment
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git pnpm

      - name: Create a non-root user for building
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build the package
        run: sudo -u builder makepkg -s --noconfirm
        working-directory: ${{ github.workspace }}
        
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package
          path: ./*.pkg.tar.zst
        working-directory: ${{ github.workspace }}
